### ISSUE TITLE
Support for embedded objects of multiple types

### ISSUE THREAD

**Issue by kop** [yii2tech/embedded#7]
Hi.

Thank you for this extension, it's very useful. However, I wanted to ask, is it possible to implement embedding of objects of different types in the same field?

For example, my current use case is that I want to implement an array field that can contain objects of different types.

**Comment by klimov-paul** [comment]
You may declare embedded mapping depending on some internal data:

``` php
public function embedProfile()
{
    $className = $this->myField === self::MAGIC_VALUE ? Profile::className() : Item::className();
    return $this->mapEmbedded('profileData', $className);
}
```

Thus each container will have different embedded object type depending on its internal fields.

> my current use case is that I want to implement an array field that can contain objects of different types.

Same embedded list (declared by `mapEmbeddedList()`) can not containg objects of the different types - there is no way for its implementation. But object from the list may declare dynamic nested embedded object in the way I have shown to you.

Still, since embedded instances created via `Yii::createObject()` you may try use DI mechanisms to achieve your goal.
